### ISSUE TITLE
URL rpm signing key hosted at rabbitmq.com is broken

### ISSUE THREAD

**Issue by rolandjohann** [rabbitmq/signing-keys#1]
The URL on https://www.rabbitmq.com/install-rpm.html for fetching the rpm signing ey is broken:
https://www.rabbitmq.com/rabbitmq-release-signing-key.asc returns with 523.

As several automation tools like ansible at openstack relies on that url it would be great if this can be fixed soon.

**Comment by rolandjohann** [comment]
Just saw that there is an issue (https://github.com/rabbitmq/rabbitmq-website/issues/621) at the website repo already, created 18 minutes ago.

**Comment by lukebakken** [comment]
Hello, we are aware of this issue and are working on a fix. Please see [this](https://twitter.com/RabbitMQ/status/1060159806756057089).
